DB::table('links')->insert(array(

array( 'short' => '', 'title' => 'Тематика', 'parent' => '' ),
/*****************************************************************************/

array( 'short' => 'au', 'title' => 'автомобили и транспорт', 'parent' => '0' ),
array( 'short' => 'bi', 'title' => 'велосипеды', 'parent' => '0' ),
array( 'short' => 'biz', 'title' => 'бизнес', 'parent' => '0' ),
array( 'short' => 'bo', 'title' => 'книги', 'parent' => '0' ),
array( 'short' => 'br', 'title' => 'барахолка', 'parent' => '0' ),
array( 'short' => 'c', 'title' => 'комиксы и мультфильмы', 'parent' => '0' ),
array( 'short' => 'cul', 'title' => 'культура', 'parent' => '0' ),
array( 'short' => 'di', 'title' => 'столовая', 'parent' => '0' ),
array( 'short' => 'em', 'title' => 'другие страны и туризм', 'parent' => '0' ),
array( 'short' => 'ew', 'title' => 'конец света', 'parent' => '0' ),
array( 'short' => 'fa', 'title' => 'мода и стиль', 'parent' => '0' ),
array( 'short' => 'fiz', 'title' => 'физкультура', 'parent' => '0' ),
array( 'short' => 'fl', 'title' => 'иностранные языки', 'parent' => '0' ),
array( 'short' => 'fs', 'title' => 'фэнтези', 'parent' => '0' ),
array( 'short' => 'ftb', 'title' => 'футбол', 'parent' => '0' ),
array( 'short' => 'hh', 'title' => 'хип-хоп культура', 'parent' => '0' ),
array( 'short' => 'hi', 'title' => 'история', 'parent' => '0' ),
array( 'short' => 'me', 'title' => 'медицина', 'parent' => '0' ),
array( 'short' => 'mg', 'title' => 'магия', 'parent' => '0' ),
array( 'short' => 'mlp', 'title' => 'my little pony', 'parent' => '0' ),
array( 'short' => 'mov', 'title' => 'фильмы', 'parent' => '0' ),
array( 'short' => 'mo', 'title' => 'мотоциклы', 'parent' => '0' ),
array( 'short' => 'mu', 'title' => 'музыка', 'parent' => '0' ),
array( 'short' => 'ne', 'title' => 'животные и природа', 'parent' => '0' ),
array( 'short' => 'pvc', 'title' => 'коллекционные фигурки', 'parent' => '0' ),
array( 'short' => '', 'title' => '', 'parent' => '' ),
/*****************************************************************************/

array( 'short' => 'po', 'title' => 'политика и новости', 'parent' => '1' ),
array( 'short' => 'psy', 'title' => 'психология', 'parent' => '1' ),
array( 'short' => 're', 'title' => 'религия и философия', 'parent' => '1' ),
array( 'short' => 'sf', 'title' => 'научная фантастика', 'parent' => '1' ),
array( 'short' => 'sci', 'title' => 'наука', 'parent' => '1' ),
array( 'short' => 'sn', 'title' => 'паранормальные явления', 'parent' => '1' ),
array( 'short' => 'sp', 'title' => 'спорт', 'parent' => '1' ),
array( 'short' => 'spc', 'title' => 'космос', 'parent' => '1' ),
array( 'short' => 'tr', 'title' => 'транспорт и авиация', 'parent' => '1' ),
array( 'short' => 'tv', 'title' => 'тв', 'parent' => '1' ),
array( 'short' => 'un', 'title' => 'образование', 'parent' => '1' ),
array( 'short' => 'wh', 'title' => 'warhammer', 'parent' => '1' ),
array( 'short' => 'wm', 'title' => 'военная техника', 'parent' => '1' ),
array( 'short' => 'w', 'title' => 'оружие', 'parent' => '1' ),
array( 'short' => 'wrk', 'title' => 'работа и карьера', 'parent' => '1' ),
array( 'short' => '', 'title' => 'Творчество Техника и софт', 'parent' => '' ),
/*****************************************************************************/

array( 'short' => 'de', 'title' => 'дизайн', 'parent' => '2' ),
array( 'short' => 'diy', 'title' => 'хобби', 'parent' => '2' ),
array( 'short' => 'dom', 'title' => 'домострой', 'parent' => '2' ),
array( 'short' => 'izd', 'title' => 'издательство', 'parent' => '2' ),
array( 'short' => 'mus', 'title' => 'музыканты', 'parent' => '2' ),
array( 'short' => 'o', 'title' => 'мазня', 'parent' => '2' ),
array( 'short' => 'out', 'title' => 'активный отдых', 'parent' => '2' ),
array( 'short' => 'pa', 'title' => 'живопись', 'parent' => '2' ),
array( 'short' => 'p', 'title' => 'фото', 'parent' => '2' ),
array( 'short' => 'td', 'title' => 'трёхмерная графика', 'parent' => '2' ),
array( 'short' => 'trv', 'title' => 'путешествия', 'parent' => '2' ),
array( 'short' => 'wp', 'title' => 'обои и высокое разрешение', 'parent' => '2' ),
array( 'short' => 'cc', 'title' => 'криптовалюта', 'parent' => '2' ),
array( 'short' => 'gd', 'title' => 'gamedev', 'parent' => '2' ),
array( 'short' => 'hw', 'title' => 'железо', 'parent' => '2' ),
array( 'short' => 'mobi', 'title' => 'мобильные устройства', 'parent' => '2' ),
array( 'short' => 'pr', 'title' => 'программирование', 'parent' => '2' ),
array( 'short' => 'ra', 'title' => 'радиотехника', 'parent' => '2' ),
array( 'short' => 's', 'title' => 'программы', 'parent' => '2' ),
array( 'short' => 't', 'title' => 'техника', 'parent' => '2' ),
array( 'short' => 'web', 'title' => 'веб-мастера', 'parent' => '2' ),
array( 'short' => '', 'title' => 'Игры Японская культура', 'parent' => '' ),
/*****************************************************************************/

array( 'short' => 'bg', 'title' => 'настольные игры', 'parent' => '3' ),
array( 'short' => 'cg', 'title' => 'консоли', 'parent' => '3' ),
array( 'short' => 'gb', 'title' => 'азартные игры', 'parent' => '3' ),
array( 'short' => 'mc', 'title' => 'minecraft', 'parent' => '3' ),
array( 'short' => 'mmo', 'title' => 'MMO', 'parent' => '3' ),
array( 'short' => 'moba', 'title' => 'MOBA', 'parent' => '3' ),
array( 'short' => 'vg', 'title' => 'видеоигры', 'parent' => '3' ),
array( 'short' => 'wr', 'title' => 'текстовые игры', 'parent' => '3' ),
array( 'short' => 'tes', 'title' => 'the elder scrolls', 'parent' => '3' ),
array( 'short' => 'a', 'title' => 'аниме', 'parent' => '3' ),
array( 'short' => 'aa', 'title' => 'аниме арт', 'parent' => '3' ),
array( 'short' => 'fd', 'title' => 'фэндом', 'parent' => '3' ),
array( 'short' => 'ja', 'title' => 'японская культура', 'parent' => '3' ),
array( 'short' => 'jsf', 'title' => 'japanese street fashion', 'parent' => '3' ),
array( 'short' => 'ma', 'title' => 'манга', 'parent' => '3' ),
array( 'short' => 'rm', 'title' => 'rozen maiden', 'parent' => '3' ),
array( 'short' => 'to', 'title' => 'touhou', 'parent' => '3' ),
array( 'short' => 'vn', 'title' => 'визуальные новеллы', 'parent' => '3' ),
array( 'short' => '', 'title' => 'Разное Взрослым Пробное', 'parent' => '' ),
/*****************************************************************************/

array( 'short' => 'b', 'title' => 'бред', 'parent' => '4' ),
array( 'short' => 'abu', 'title' => 'абу', 'parent' => '4' ),
array( 'short' => 'd', 'title' => 'Дискуссии о Два.ч', 'parent' => '4' ),
array( 'short' => 'soc', 'title' => 'общение', 'parent' => '4' ),
array( 'short' => 'r', 'title' => 'просьбы', 'parent' => '4' ),
array( 'short' => 'media', 'title' => 'анимация', 'parent' => '4' ),
array( 'short' => 'int', 'title' => 'international', 'parent' => '4' ),
array( 'short' => 'chat', 'title' => 'Чат', 'parent' => '4' ),
array( 'short' => 'old', 'title' => 'O.L.D.F.A.G', 'parent' => '4' ),
array( 'short' => 'http:tv.2ch.hk', 'title' => '2chTV', 'parent' => '4' ),
array( 'short' => 'fg', 'title' => 'трапы', 'parent' => '4' ),
array( 'short' => 'fur', 'title' => 'фурри', 'parent' => '4' ),
array( 'short' => 'g', 'title' => 'девушки', 'parent' => '4' ),
array( 'short' => 'ga', 'title' => 'геи', 'parent' => '4' ),
array( 'short' => 'h', 'title' => 'хентай', 'parent' => '4' ),
array( 'short' => 'fag', 'title' => 'FAGS', 'parent' => '4' ),
array( 'short' => 'ho', 'title' => 'прочий хентай', 'parent' => '4' ),
array( 'short' => 'hc', 'title' => 'hardcore', 'parent' => '4' ),
array( 'short' => 'e', 'title' => 'extreme pron', 'parent' => '4' ),
array( 'short' => 'fet', 'title' => 'фетиш', 'parent' => '4' ),
array( 'short' => 'sex', 'title' => 'секс и отношения', 'parent' => '4' ),
array( 'short' => 'zog', 'title' => 'теории заговора', 'parent' => '4' ),
array( 'short' => 'guro', 'title' => 'guro (18+)', 'parent' => '4' ),
array( 'short' => 'ussr', 'title' => 'советский союз', 'parent' => '4' ),
array( 'short' => 'ukr', 'title' => 'Ukraine', 'parent' => '4' ),
));